name: Continuous Deploy #action名称
on: [push] #在推送的时候运行此action

jobs:
  deploy_job:
    runs-on: ubuntu-latest  #运行环境
    name: sftp
    steps:
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.5
      with:  
        username: 'dzhou'   #ssh user name
        server: 'people.reed.edu' #引用之前创建好的secret
        ssh_private_key: ${{ secrets.REED_PASSWORD }} #引用之前创建好的secret
        local_path: './*'  # 对应我们项目build的文件夹路径
        remote_path: '/'
        sftp_only: true
